### ISSUE TITLE
no space between keyword and name

### ISSUE THREAD

**Issue by tewarid** [sourcey/moxygen#22]
In the summary, keywords such as define, enum, and class, don't have a space before the name e.g. `classClass` instead of `class Call`.

**Comment by tewarid** [comment]
Seems to be a problem with VS Code's markdown preview plugin.

**Comment by ntonnaett** [comment]
MkDocs has the same problem. It would be fixed with this change:
```
`class `[`JitterBuffer`]
`class` [`JitterBuffer`]
```
As the second is easier to read, it would be great to have this changed in moxygen.
