### ISSUE TITLE
Anchors in markdown

### ISSUE THREAD

**Issue by eLod** [sourcey/moxygen#31]
i noticed the anchors (refs) are converted to `{#refid}` in markdown and was wondering if that is some de-facto syntax, or why it is done that way. i am using remark to convert the mds to html, but it does not seem to be supporting it. a quick search also didn't yield any common agreed pattern to use, other than effectively pushing `<a name/id="refid"></a>` into the md content. would you approve a pr doing that?

**Comment by auscaster** [comment]
This syntax is a feature of markdown extra https://michelf.ca/projects/php-markdown/extra/#spe-attr. Thanks for the PR though, I'll get that merged in :)
