### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\path\to\project\tmp\test-Cartography::CartMath.md'

### ISSUE THREAD

**Issue by chrisui** [sourcey/moxygen#43]
I get the titled error when attempting to output a new markdown file per class (-c). First glance this appears to be a problem with not validating the filename output? Ie. `::` is invalid in file name.

```
$ moxygen -c -o "tmp/test-%s.md"  .\doxygen\xml\
```

**Comment by chrisui** [comment]
Have confirmed a naive `e.name.replace(/\:/g, '-')`  solution resolved my issue here. 

Happy to submit a PR if you have some preference on how to tackle this in a more robust way?

**Comment by JunyiXiao** [comment]
We are blocked by the same issue and comfirmed that your solution works for us as well. Do you wanna to put up the PR? or I can submit the PR for you if you don't mind.

**Comment by JunyiXiao** [comment]
@chrisui I went ahead and create the pull request: https://github.com/sourcey/moxygen/pull/46

**Comment by auscaster** [comment]
Thanks guys, just merged! :)
